# Adapted from dfm/george

language: python

matrix:
  include:
    - python: 3.5

git:
    submodules: true

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  
install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes numpy scipy matplotlib nose numba pandas
  - ln -sf $(which gcc) x86_64-conda_cos6-linux-gnu-gcc
  - python setup.py develop

# Configure a headless display to test plot generation
# http://stackoverflow.com/a/35403128
before_script: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Give xvfb some time to start
  - sleep 3 

script: 
  - nosetests --with-coverage --cover-package=planetplanet -v -w tests

addons:
  apt:
    packages:
      libgsl0-dev
