#!/bin/sh

# Prevent numpy from multithreading
export OPENBLAS_NUM_THREADS=1

# CD into our working directory
cd ${HISTPATH}

if [ $NODES -eq 1 ]; then
    # Run on a single node with Python multiprocessing
    python -c "import hist; hist._Parallelize($NSAMP, $PHOTO, $EYEBALL, $BATCHSZ)"
else
    # Run on multiple nodes with MPI
    mpirun -np $PBS_NP python -c "import hist; hist._Parallelize($NSAMP, $PHOTO, $EYEBALL, $BATCHSZ)" 
fi